name: wonders
description: Explore the famous wonders of the world.
publish_to: "none"
version: 2.2.2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  collection: ^1.17.0
  cupertino_icons: ^1.0.5
  desktop_window: ^0.4.0
  drop_cap_text: ^1.1.3
  equatable: ^2.0.5
  extra_alignments: ^1.0.0+1
  flextras: ^1.0.0
  flutter_animate: ^4.5.0
  flutter_circular_text: ^0.3.1
  flutter_displaymode: ^0.6.0
  flutter_native_splash: ^2.3.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.1
  gap: ^3.0.1
  get_it: ^7.2.0
  get_it_mixin: ^4.2.2
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+3
  go_router: ^13.0.1
  home_widget: ^0.4.1 # use the forked version when on `main` flutter branch
#    git:
#      url: https://github.com/gskinnerTeam/flutter_home_widget_fork.git
  http: ^1.1.0
  image: ^4.1.3
  image_fade: ^0.6.2
  image_gallery_saver: ^2.0.3
  intl: ^0.18.1
  internet_connection_checker: ^1.0.0+1
  package_info_plus: ^5.0.0
  particle_field: ^1.0.0
  path_provider: ^2.1.1
  pointer_interceptor: ^0.9.3+6
  provider: ^6.0.5
  rnd: ^0.2.0
  shared_preferences: ^2.0.17
  sized_context: ^1.0.0+1
  smooth_page_indicator: ^1.0.1
  unsplash_client: ^2.1.0+3
  url_launcher: ^6.1.14
  webview_flutter: ^4.0.2
  youtube_player_iframe: ^4.0.4

dev_dependencies:
  icons_launcher: ^2.1.3
  flutter_lints: ^2.0.2
  dependency_validator: ^3.2.2

icons_launcher:
  image_path: "assets/marketing/app-icon-1024.png"
  platforms:
    web:
      enable: true
      image_path: "assets/marketing/app-icon-512.png"
      favicon_path: "assets/marketing/app-icon-512.png"
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true

flutter_icons:
  ios: true
  android: true
  image_path: "assets/marketing/app-icon-1024.png"

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/_common/
    - assets/images/_common/icons/
    - assets/images/_common/texture/
    - assets/images/chichen_itza/
    - assets/images/christ_the_redeemer/
    - assets/images/colosseum/
    - assets/images/great_wall_of_china/
    - assets/images/machu_picchu/
    - assets/images/petra/
    - assets/images/pyramids/
    - assets/images/taj_mahal/
    - assets/images/collectibles/
    - assets/images/widget/

  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/CinzelDecorative-Regular.ttf
        - asset: assets/fonts/CinzelDecorative-Black.ttf
        - asset: assets/fonts/CinzelDecorative-Bold.ttf
    - family: Yeseva
      fonts:
        - asset: assets/fonts/YesevaOne-Regular.ttf
    - family: Tenor
      fonts:
        - asset: assets/fonts/TenorSans-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
    - family: MaShanZheng
      fonts:
        - asset: assets/fonts/MaShanZheng-Regular.ttf
    - family: B612Mono
      fonts:
        - asset: assets/fonts/B612Mono-Regular.ttf
